import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
const linkStyle = { marginRight: 15 };
const Header = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <a>asd</a>
    </Head>
  </div>
);
export default Header;
